# Generated by Django 2.0 on 2018-01-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='fuckyou',
            field=models.BooleanField(default=True),
        ),
    ]
